name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Docker login
      run: echo ${{ secrets.DOCKER_ACCESS_TOKEN}} | docker login -u ${{ secrets.DOCKER_USERNAME}} --password-stdin

    - name: Build and push Frontend docker image
      working-directory: ./frontend
      run: |
        docker build -t partheev8/nutri-frontend:latest .
        docker push partheev8/nutri-frontend:latest
        
    - name: Build and push Backend docker image
      working-directory: ./backend
      run: |
        docker build -t partheev8/nutri-backend:latest .
        docker push partheev8/nutri-backend:latest
        
    - name: Build and push AI Backend service docker image
      working-directory: ./ai-food-detection  
      run: |
        docker build -t partheev8/nutri-ai:latest .
        docker push partheev8/nutri-ai:latest
       
